import crypto from 'crypto';
import Groq from 'groq-sdk';
import { db } from '@/lib/db';
import { documentationVersions, DocumentationVersion } from '@/db/schema';
import { getAnalysisById, getRepoById } from '@/lib/db-service';
import { verifyDocumentation } from '@/lib/verification/documentation-verifier';
import { eq } from 'drizzle-orm';

export async function generateVerifiedDocumentation(
  repoId: string,
  analysisId: string
): Promise<DocumentationVersion> {
  const repo = await getRepoById(repoId);
  const analysis = await getAnalysisById(analysisId);

  if (!repo || !analysis) {
    throw new Error('Repository or Analysis record not found');
  }

  const archData = (analysis.architecture_data as Record<string, unknown>) || {};
  const modules = (archData.modules as Array<{ path: string }>) || [];
  const mermaidDiagram = analysis.mermaid_diagram || '';

  const apiKey = process.env.GROQ_API_KEY;

  let currentContent = '';
  let verification = { isValid: false, errors: ['Not generated'], warnings: [] as string[] };
  let attempts = 0;
  const maxAttempts = 3;

  while (attempts < maxAttempts && !verification.isValid) {
    attempts++;
    console.log(`[Doc Generator] Generation attempt ${attempts}/${maxAttempts} for repo ${repo.full_name}`);

    if (apiKey) {
      try {
        const groq = new Groq({ apiKey });

        const promptFeedback =
          verification.errors.length > 0 && currentContent
            ? `\nPREVIOUS GENERATION VERIFICATION ERRORS TO FIX:\n${verification.errors.join('\n')}\n`
            : '';

        const userPrompt = `Generate a high quality, comprehensive README.md for repository '${repo.full_name}'.

REPOSITORY FACTS:
- Default Branch: ${repo.default_branch}
- Commit SHA: ${analysis.commit_sha || 'head'}
- Module Count: ${modules.length}
- Detected Modules: ${modules.slice(0, 30).map((m) => m.path).join(', ')}

ARCHITECTURE MERMAID DIAGRAM:
\`\`\`mermaid
${mermaidDiagram}
\`\`\`
${promptFeedback}
REQUIREMENTS:
1. Start with '# ${repo.full_name}' title header.
2. Include sections for Overview, System Architecture (with the provided Mermaid diagram), Repository Structure, and Getting Started.
3. Do NOT invent fake files or secret values.
4. Output raw markdown.`;

        const res = await groq.chat.completions.create({
          messages: [
            {
              role: 'system',
              content:
                'You are IntentMesh Technical Documentation Engineer. Generate accurate, grounded README.md documentation for GitHub repositories based strictly on observed static analysis evidence.',
            },
            { role: 'user', content: userPrompt },
          ],
          model: 'llama-3.3-70b-versatile',
          temperature: 0.3,
          max_completion_tokens: 2048,
        });

        currentContent = res.choices[0]?.message?.content || '';
      } catch (err) {
        console.error(`[Doc Generator] Groq API call failed on attempt ${attempts}:`, err);
      }
    }

    // Fallback documentation template if Groq API key is missing or fails
    if (!currentContent) {
      currentContent = `# ${repo.full_name}

## Overview
IntentMesh Code Intelligence analysis for \`${repo.full_name}\`.

## System Architecture

\`\`\`mermaid
${mermaidDiagram || 'graph TD\n    A[Root] --> B[Src]'}
\`\`\`

## Repository Structure
Analyzed commit SHA: \`${(analysis.commit_sha || 'head').substring(0, 7)}\`
Total Modules Detected: ${modules.length}

### Key Modules
${modules.slice(0, 15).map((m) => `- \`${m.path}\``).join('\n')}

---
*Generated by IntentMesh Code Intelligence Platform*`;
    }

    // Run deterministic verification
    verification = verifyDocumentation(currentContent, modules);
  }

  const contentHash = crypto.createHash('sha256').update(currentContent).digest('hex');
  const status = verification.isValid ? 'verified' : 'failed';
  const notes = [...verification.errors, ...verification.warnings].join('; ');

  const [docVersion] = await db
    .insert(documentationVersions)
    .values({
      repo_id: repoId,
      analysis_id: analysisId,
      document_type: 'README.md',
      content: currentContent,
      content_hash: contentHash,
      status,
      verification_notes: notes || 'Passed verification cleanly',
    })
    .returning();

  return docVersion;
}

export async function getLatestDocVersion(repoId: string): Promise<DocumentationVersion | null> {
  const res = await db
    .select()
    .from(documentationVersions)
    .where(eq(documentationVersions.repo_id, repoId))
    .limit(1);
  return res[0] ?? null;
}
