import { getOctokit } from '@/lib/github';

export interface PullRequestResult {
  branchName: string;
  pullRequestNumber: number;
  pullRequestUrl: string;
}

export async function createDocumentationPullRequest(
  accessToken: string,
  owner: string,
  repo: string,
  docVersion: { id: string; content: string },
  defaultBranch: string
): Promise<PullRequestResult> {
  const octokit = getOctokit(accessToken);
  const branchName = `intentmesh/docs/${docVersion.id.substring(0, 8)}`;

  // 1. Get SHA of default branch HEAD
  const { data: refData } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const baseSha = refData.object.sha;

  // 2. Create or verify target branch
  try {
    await octokit.rest.git.getRef({ owner, repo, ref: `heads/${branchName}` });
    console.log(`[GitHub PR] Branch ${branchName} already exists, updating content.`);
  } catch (err: unknown) {
    const error = err as { status?: number };
    if (error.status === 404) {
      await octokit.rest.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });
      console.log(`[GitHub PR] Created branch ${branchName} from ${baseSha.substring(0, 7)}`);
    } else {
      throw err;
    }
  }

  // 3. Get existing README file sha on target branch if it exists
  let fileSha: string | undefined;
  try {
    const { data: fileData } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path: 'README.md',
      ref: branchName,
    });
    if ('sha' in fileData) {
      fileSha = fileData.sha;
    }
  } catch (err: unknown) {
    const error = err as { status?: number };
    if (error.status !== 404) throw err;
  }

  // 4. Commit README.md to branch
  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: 'README.md',
    message: 'docs: Update README.md generated by IntentMesh',
    content: Buffer.from(docVersion.content, 'utf-8').toString('base64'),
    branch: branchName,
    sha: fileSha,
  });

  // 5. Create Pull Request
  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: 'docs: Update README.md (IntentMesh Code Intelligence)',
    head: branchName,
    base: defaultBranch,
    body: `### 🤖 IntentMesh Automated Documentation Update\n\nThis Pull Request was generated by **IntentMesh Code Intelligence** based on deterministic static analysis and grounded repository evidence.\n\n- **Document**: \`README.md\`\n- **Version ID**: \`${docVersion.id}\`\n\nPlease review and merge when ready!`,
  });

  return {
    branchName,
    pullRequestNumber: pr.number,
    pullRequestUrl: pr.html_url,
  };
}
