import Groq from 'groq-sdk';
import { ContextChunk } from '@/lib/retrieval';

export async function generateGroundedAnswer(
  query: string,
  contextChunks: ContextChunk[],
  architectureData?: unknown
): Promise<{ answer: string; sources: Array<{ filePath: string; chunkIndex: number }> }> {
  const apiKey = process.env.GROQ_API_KEY;

  const sources = contextChunks.map((c) => ({
    filePath: c.file_path,
    chunkIndex: c.chunk_index,
  }));

  // Fallback response if no relevant chunks found or low confidence
  if (contextChunks.length === 0 || contextChunks.every((c) => c.similarity < 0.05)) {
    return {
      answer:
        'The available repository evidence is insufficient to answer your question confidently. Please complete or re-run repository analysis to ensure files are indexed.',
      sources: [],
    };
  }

  // Format retrieved chunks context
  const contextFormatted = contextChunks
    .map((c, i) => `[Source ${i + 1}: ${c.file_path} (chunk #${c.chunk_index})]\n${c.content}`)
    .join('\n\n---\n\n');

  // Format optional architecture summary facts
  let archSummary = '';
  if (architectureData && typeof architectureData === 'object' && 'metadata' in architectureData) {
    archSummary = `Repository Metadata: ${JSON.stringify((architectureData as Record<string, unknown>).metadata)}\n`;
  }

  const systemPrompt = `You are IntentMesh Code Intelligence Assistant.
Your task is to answer developer questions about a GitHub repository based ONLY on the provided repository context chunks and architecture facts.

CRITICAL GROUNDING RULES:
1. Answer strictly using observed repository evidence from the context below.
2. Do NOT invent or hallucinate file names, function names, APIs, or dependencies.
3. Cite source file paths explicitly when referencing code or configuration (e.g. \`lib/auth.ts\`).
4. Clearly distinguish directly observed facts from developer inferences.
5. If the provided context does NOT contain enough information to answer, state clearly: "The available repository evidence is insufficient to answer this question."`;

  const userPrompt = `${archSummary}RELEVANT REPOSITORY CONTEXT:
${contextFormatted}

USER QUESTION:
${query}

PROVIDE A GROUNDED ANSWER WITH FILE CITATIONS:`;

  if (!apiKey) {
    // If GROQ_API_KEY is not configured in env, provide clear grounded synthesis fallback
    const topFiles = Array.from(new Set(contextChunks.map((c) => c.file_path)));
    return {
      answer: `Based on the repository source files (${topFiles.join(', ')}):\n\n${contextChunks[0]?.content.slice(0, 500)}...\n\n(Set GROQ_API_KEY in .env.local to enable full Groq LLM synthesis)`,
      sources,
    };
  }

  try {
    const groq = new Groq({ apiKey });
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.2,
      max_completion_tokens: 1024,
    });

    const answer = chatCompletion.choices[0]?.message?.content || 'No response generated by model.';
    return { answer, sources };
  } catch (err) {
    console.error('[Groq] Failed calling Groq API:', err);
    // Fallback if model call fails
    return {
      answer: `Grounded evidence found in: ${sources.map((s) => s.filePath).join(', ')}. (Groq API call failed or timed out).`,
      sources,
    };
  }
}
