import { NextRequest, NextResponse } from 'next/server';

// Pushes a file to a GitHub repo using the Contents API
async function pushFile(
  accessToken: string,
  owner: string,
  repo: string,
  path: string,
  content: string,
  message: string
) {
  // Check if file already exists (to get its SHA for update)
  let sha: string | undefined;
  const checkRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        Accept: 'application/vnd.github+json',
      },
    }
  );
  if (checkRes.ok) {
    const existing = await checkRes.json();
    sha = existing.sha;
  }

  // Push the file
  const body: Record<string, unknown> = {
    message,
    content: Buffer.from(content).toString('base64'),
  };
  if (sha) body.sha = sha; // Required for updates

  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    }
  );

  if (!res.ok) {
    const err = await res.json();
    throw new Error(err.message || `Failed to push ${path}`);
  }

  return res.json();
}

export async function POST(request: NextRequest) {
  try {
    const { accessToken, owner, repo, readme, diagram, replaceReadme } =
      await request.json();

    if (!accessToken || !owner || !repo || !readme || !diagram) {
      return NextResponse.json({ error: 'Missing required fields.' }, { status: 400 });
    }

    // Determine README filename based on user's choice
    const readmePath = replaceReadme ? 'README.md' : 'README-intentmesh.md';

    // Architecture markdown file with the Mermaid diagram
    const architectureContent = `# Architecture Diagram

Generated by [IntentMesh](https://intentmesh.vercel.app)

\`\`\`mermaid
${diagram}
\`\`\`
`;

    // Push both files in parallel
    await Promise.all([
      pushFile(
        accessToken, owner, repo,
        readmePath, readme,
        '📝 Add IntentMesh generated README'
      ),
      pushFile(
        accessToken, owner, repo,
        'architecture.md', architectureContent,
        '❋ Add IntentMesh architecture diagram'
      ),
    ]);

    return NextResponse.json({ success: true });

  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}